apiVersion: v1
kind: Service
metadata:
   name: admin-server
   labels:
      app: admin-server

spec:
  ports:
    - port: 7001
      nodePort: 32001
      targetPort: weblogic-port
      name: weblogic-port
  clusterIP: 10.105.160.78
  
  selector:
    app: admin-server

 # type: NodePort
  type: NodePort
