kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-claim-weblogic
spec:
  storageClassName: storage-weblogic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

