apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: managed-server
spec:
  serviceName: managed-server-service
  replicas: 2
  template:
    metadata:
      name: ms
      labels:
        app: managed-server
    spec:
      subdomain: managed-server-service
      containers:
      - name: managed-server
        image: ashniku123/weblogic12.2.1.3:withoutDB
        command: ["/u01/oracle/createServer.sh"]
        ports:
        - containerPort: 8001
          name: ms1-port
        env:
        - name: ADMIN_HOST
          value: admin-server
        - name: MS_PORT
          value: "8001"
        - name: MS_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

        volumeMounts:
          - mountPath: /u01/oracle/user_projects
            name: weblogic-storage

      volumes:
        - name: weblogic-storage
          persistentVolumeClaim:
            claimName: pv-claim-weblogic

  selector:
    matchLabels:
      app: managed-server

---

apiVersion: v1
kind: Service
metadata:
  name: managed-server
  labels:
    app: managed-server
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8001
  clusterIP: None
  selector:
    app: managed-server
