kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: weblogic-access
rules:
- apiGroups: [""]
  resources: ["pods","secret","replicationController"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments","statefulSet"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: weblogic-access-rolebind
  namespace: default
subjects:
- kind: Group
  name: weblogic-group
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: weblogic-access
  apiGroup: rbac.authorization.k8s.io
